question_data =  [
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy", "question": "What does CPU stand for?",
     "correct_answer": "Central Processing Unit",
     "incorrect_answers": ["Central Process Unit", "Computer Personal Unit", "Central Processor Unit"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "If you were to code software in this language you&#039;d only be able to type 0&#039;s and 1&#039;s.",
     "correct_answer": "Binary", "incorrect_answers": ["JavaScript", "C++", "Python"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "What does the Prt Sc button do?",
     "correct_answer": "Captures what&#039;s on the screen and copies it to your clipboard",
     "incorrect_answers": ["Nothing",
                           "Saves a .png file of what&#039;s on the screen in your screenshots folder in photos",
                           "Closes all windows"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "What is the most preferred image format used for logos in the Wikimedia database?",
     "correct_answer": ".svg", "incorrect_answers": [".png", ".jpeg", ".gif"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "In web design, what does CSS stand for?", "correct_answer": "Cascading Style Sheet",
     "incorrect_answers": ["Counter Strike: Source", "Corrective Style Sheet", "Computer Style Sheet"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "How many kilobytes in one gigabyte (in decimal)?", "correct_answer": "1000000",
     "incorrect_answers": ["1024", "1000", "1048576"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "On Twitter, what was the original character limit for a Tweet?", "correct_answer": "140",
     "incorrect_answers": ["120", "160", "100"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "In &quot;Hexadecimal&quot;, what color would be displayed from the color code? &quot;#00FF00&quot;?",
     "correct_answer": "Green", "incorrect_answers": ["Red", "Blue", "Yellow"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "The C programming language was created by this American computer scientist. ",
     "correct_answer": "Dennis Ritchie",
     "incorrect_answers": ["Tim Berners Lee", "al-Khw\u0101rizm\u012b", "Willis Ware"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "What language does Node.js use?", "correct_answer": "JavaScript",
     "incorrect_answers": ["Java", "Java Source", "Joomla Source Code"]}
]
